### ISSUE TITLE
display error after nii export

### ISSUE THREAD

**Issue by ingo-m** [ofgulban/segmentator#10]
Bug in segmentator-devel-marian:

When using the lasso again after exporting an nii file, the selection in the volume view is corrupted (see screenshot).

![err](https://cloud.githubusercontent.com/assets/10960892/17101083/cbcb9b7a-5272-11e6-89b8-ad29cdff52ed.png)

**Comment by ofgulban** [comment]
@MSchnei does this happen in devel-marian branch?

**Comment by ofgulban** [comment]
@MSchnei did we solve this issue?

**Comment by ofgulban** [comment]
This bug is now fixed.
