### ISSUE TITLE
Deriche filter for gradient calculation (branch: devel-marian)

### ISSUE THREAD

**Issue by MSchnei** [ofgulban/segmentator#12]
@ofgulban: knows what to do.

**Comment by ofgulban** [comment]
I have implemented 3D Deriche filter however it is slow. For an mri image size 320x320x256 it takes around 15 minutes to calculate the gradients in my workstation.

For this reason, I have added an option to load any gradient magnitude image (actually any image can be loaded but it is intended and tested for gradient magnitute). 
___
#### Gradient magnitude images:
np.gradient
<img src="https://cloud.githubusercontent.com/assets/4668327/18609998/2ffcdc04-7d10-11e6-878e-2504b8f25a08.png" width="400">

3D_Deriche with alpha=2
<img src="https://cloud.githubusercontent.com/assets/4668327/18610000/34966ba4-7d10-11e6-8574-9d0863399034.png" width="400"> 

3D_Deriche with alpha=1
<img src="https://cloud.githubusercontent.com/assets/4668327/18610001/378ea092-7d10-11e6-9578-42efefeac80d.png"  width="400">
___
#### Volume histograms from the same data:
np.gradient
<img src="https://cloud.githubusercontent.com/assets/4668327/18610025/1fe180a8-7d11-11e6-862d-f6e4dfb0b43c.png"  width="200">

3D_Deriche with alpha=2
<img src="https://cloud.githubusercontent.com/assets/4668327/18610026/233453ac-7d11-11e6-8377-bb5b60a4b0fb.png"  width="200">

___

I am not sure this filter should be included in segmentator in its current form, at least for the next version (v1.1.0). We need to understand how it effects the volume histogram and whether the current masking methods are enough. Probably normalized graph cuts will work better with deriche filter compared to the sector mask.

**Comment by ofgulban** [comment]
As a workaround for the long computation time, now users can load an already computed gradient magnitude image with "--gramag" flag.

**Comment by ofgulban** [comment]
The computation time of Deriche filter is greatly reduced by using cython. First time users of this filter should change directory to segmentator folder and run:

```python setup.py build_ext --inplace``` 

Make sure that you have cython installed (```pip install cython``` or ```conda install cython```)

**Comment by ofgulban** [comment]
Although it can be optimized further for faster calculation, implementation of Deriche filter gradient magnitude seems fine.
