### ISSUE TITLE
contours for ncut labels visualization (branch devel-marian)

### ISSUE THREAD

**Issue by ofgulban** [ofgulban/segmentator#17]
It seems, it is quite hard distinguish numerically close labels only by looking at their colors. I think it would be better if the visualize ncut labels with black contours (like political maps).

http://colorbrewer2.org/#type=qualitative&scheme=Paired&n=12

**Comment by MSchnei** [comment]
![screenshot from 2016-09-09 20 00 10](https://cloud.githubusercontent.com/assets/15090072/18397387/447c9f96-76c8-11e6-8007-8639e6fdf080.png)

The first implementation, now on

**Comment by ofgulban** [comment]
This is great. Looks really useful. One issue that needs to be fixed is when the user starts re-labeling the ncut labels, the contours does not merge.
I think it would be more intuitive if the contours merge when the neighboring labels becomes the same.

**Comment by ofgulban** [comment]
Now the contours are merging/splitting properly after each click.
