### ISSUE TITLE
Ability to make colours transparent and choose particular colors (branch: devel-Marian)

### ISSUE THREAD

**Issue by MSchnei** [ofgulban/segmentator#18]
- [x] Add ability to set colors in the ncut version to transparent.
- [x] Add (for example) radio buttons to add particular colors for labeling segments.

**Comment by ofgulban** [comment]
Label 0 is now transparent in ncut labels.

**Comment by ofgulban** [comment]
Radio buttons are now added (they look ugly though). They are quite useful for quick re-labeling.

**Comment by MSchnei** [comment]
This is working for now, labels can be set transparent with right mouse button, when radio button 0 or value 0 for slider is selected.
