### ISSUE TITLE
Resetting labels for ncut after having set particular colors (branch: devel-Marian)

### ISSUE THREAD

**Issue by MSchnei** [ofgulban/segmentator#19]
After setting your own colors on ncut labels and hitting the reset button there seems to be a problem with updating and colours are only reset (partially) when one clicks on the left figures

**Comment by ofgulban** [comment]
Fixed. Can you also check and if it is working fine close this issue afterwards.

**Comment by MSchnei** [comment]
everything seems to be working. very clear interface now.
