### ISSUE TITLE
Histogram normalization

### ISSUE THREAD

**Issue by MSchnei** [ofgulban/segmentator#20]
Research and implement current cutting-edge method for histogram normalization

**Comment by ofgulban** [comment]
Well we are doing histogram normalization(see the grayscale images section [here](http://www.ipol.im/pub/art/2011/llmps-scb/) ), or do you mean histogram matching?

**Comment by ofgulban** [comment]
I think this is out of our scope. Histogram normalization can be done before segmentator.
