### ISSUE TITLE
Calculate entropy to guide decision of users for next ncut (branch: devel-marian)

### ISSUE THREAD

**Issue by MSchnei** [ofgulban/segmentator#29]
#### Reference

Ip, C. Y., Varshney, A., & Jaja, J. (2012). Hierarchical exploration of volumes using multilevel segmentation of the intensity-gradient histograms. IEEE Transactions on Visualization and Computer Graphics, 18(12), 2355–2363. http://doi.org/10.1109/TVCG.2012.231

**Comment by ofgulban** [comment]
@MSchnei  any plans on this? I think your branch exploring this feature is quite outdated now.

**Comment by MSchnei** [comment]
Yes, the branch is outdated, although I would not delete it yet since it contains code that can be used if we want to implement entropy-guided decisions. I have no immediate plans for implementation.

**Comment by ofgulban** [comment]
I am closing this until one day if we decide to pursue this again.
