### ISSUE TITLE
Make the toggling of transparency dependent on position of mouse cursor (ncut version)

### ISSUE THREAD

**Issue by MSchnei** [ofgulban/segmentator#33]
when mouse cursor is over right graph, toggle image mask. when mouse cursor is over left graph toggle ncut mask.

**Comment by ofgulban** [comment]
I guess you are planning to use the same toggle button for both, right? I am not sure that this will be easier than having two separate buttons and not tracking the cursor position.

**Comment by ofgulban** [comment]
@MSchnei should we close this issue?

**Comment by ofgulban** [comment]
I am closing this. It seems that there is no plan to implement it anytime soon and we can live without it.
