### ISSUE TITLE
Unable to run segmentator with mp2rage data on debain

### ISSUE THREAD

**Issue by ingo-m** [ofgulban/segmentator#40]
When trying to load a T1 mp2rage image with segmentator (main branch), the following error occurs:

`john@FDPMW2379:~/PhD/GitHub/segmentator$ python segmentator.py /home/john/Desktop/20161205/mp2rage_t1_up.nii.gz`
`Traceback (most recent call last):`
`  File "segmentator.py", line 49, in <module>`
`    import segmentator_main`
`  File "/home/john/PhD/GitHub/segmentator/segmentator_main.py", line 22`
`    from __future__ import division`
`SyntaxError: from __future__ imports must occur at the beginning of the file`

My OS is debian 8. All python dependencies should be ok:

`>>> import numpy as np`
`>>> np.__version__`
`'1.11.2'`
`>>> import matplotlib as lib`
`>>> lib.__version__`
`'1.5.3'`
`>>> import nibabel as nib`
`>>> nib.__version__`
`'2.1.0'`

**Comment by MSchnei** [comment]
Faruk,
Could this be related to recent pruning and "cosmetics" activities? Maybe having two doc strings before import division is one too much?

**Comment by ingo-m** [comment]
Yes but I can't push it.

**Comment by MSchnei** [comment]
Ok, pull request by @ingo-m  has been accepted and merged. Problem should be fixed now.

**Comment by ofgulban** [comment]
I didn't know this. Here is a relevant stackoverflow post for future reference:

http://stackoverflow.com/questions/38688504/from-future-imports-must-occur-at-the-beginning-of-the-file-what-defines
