### ISSUE TITLE
Use medpy for aniso_diff_3D

### ISSUE THREAD

**Issue by cancan101** [ofgulban/segmentator#62]
medpy has a newer / cleaner version of the `aniso_diff_3D` function. See: http://loli.github.io/medpy/generated/medpy.filter.smoothing.anisotropic_diffusion.html#medpy.filter.smoothing.anisotropic_diffusion.

**Comment by ofgulban** [comment]
Thanks for the suggestion Alex, we will have a look into this.

**Comment by ofgulban** [comment]
I have removed this function with da50791647ca4aee1ed32a516296734281a2544d
Closing issue.

**Comment by ofgulban** [comment]
@cancan101 thanks for your efforts though. I will keep checking medpy, seems like a cool project.
