### ISSUE TITLE
installation seems to have worked, error to run segmentator though

### ISSUE THREAD

**Issue by katjaq** [ofgulban/segmentator#66]
Hi! I am working on MacOs. I cloned the repo and then followed the instructions – installing the requirements logged to my terminal that it found my scipy and some other modules, successfully uninstalled them, and installed them again in a newer version... looks like in the same place and everything should be fine.

The next installation / setup steps worked fine as well (console log looked fine), however, trying to run segmentator throws me an error you may have seen before and have some help comments already
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

I am afraid now, because I am doing my PhD (and have to finish so terribly soon) and have plenty of scripts and notebooks running all fine with python 2.7 as is (within the anaconda distribution). Replacing python by pythonw where? I am sorry, I am just afraid of breaking other important stuff :/ Any idea?
Many thanks!

**Comment by ofgulban** [comment]
Thanks for the report, the issue is addressed with commit ee8f8db87e4627cbf8f793f5b490f7b082554292 
We will soon merge it to the master and publish a new version.
