### ISSUE TITLE
Unable to run segmentator_filters

### ISSUE THREAD

**Issue by andrewtmorgan** [ofgulban/segmentator#78]
I am trying to run segmentator_filters, but my system is not able to find the config_filters module. I have tried adding the segmentator directory to $PYTHONPATH, but that didn't change things. Any help with this would be greatly appreciated.

Here is the traceback:

```
$ segmentator_filters data.nii.gz --nr_iterations 5
=================
Segmentator 1.5.2
=================
Filters initiated...
Traceback (most recent call last):
  File "/home/am/nipype/venv/bin/segmentator_filters", line 11, in <module>
    load_entry_point('segmentator==1.5.2', 'console_scripts', 'segmentator_filters')()
  File "/home/am/nipype/venv/lib/python3.6/site-packages/segmentator-1.5.2-py3.6-linux-x86_64.egg/segmentator/filters_ui.py", line 94, in main
  File "/home/am/nipype/venv/lib/python3.6/site-packages/segmentator-1.5.2-py3.6-linux-x86_64.egg/segmentator/filter.py", line 23, in <module>
ModuleNotFoundError: No module named 'config_filters'
```

**Comment by ofgulban** [comment]
Hi Andrew,

Thanks for the bug report. Could you try clone and install from [devel branch](https://github.com/ofgulban/segmentator/tree/devel) and try again?

Let me know it it still doesn't work.

**Comment by andrewtmorgan** [comment]
Hi Faruk,

Thanks for your message. Things look the same after having installed the development branch.

Is there any more info I can give you to help?

Thanks again,
Tyler

**Comment by ofgulban** [comment]
Did you try it from a fresh virtual environment? Because I cannot replicate the error now.

**Comment by ofgulban** [comment]
Nevermind I saw the what I have missed, I will push to devel soon.

**Comment by ofgulban** [comment]
Oh, could it be the case that you did not do `git checkout devel` after cloning and before installing? Because I am pretty sure [this commit](https://github.com/ofgulban/segmentator/commit/c38ab7a87aa2a1bc1567bbba0e44f252ddb6e720) solves the issue.

**Comment by andrewtmorgan** [comment]
Okay, yeah that was it. All good now!

**Comment by ofgulban** [comment]
Great, thanks !
