### ISSUE TITLE
Compoda not installed during setup

### ISSUE THREAD

**Issue by sitek** [ofgulban/segmentator#83]
After following the instructions in the README [here](https://github.com/ofgulban/segmentator#installation--quick-start), running `segmentator_filters {file}` resulted in `ModuleNotFoundError: No module named 'compoda'`.

Manually installing with `pip install compoda`, it now runs fine.

**Comment by ofgulban** [comment]
Thanks @sitek , I will incorporate this in the next release.

**Comment by ofgulban** [comment]
Done.
