### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by ingo-m** [ofgulban/segmentator#85]
@ofgulban: When checking #84 I downloaded the zip archive of the latest release as recommended on segmentator's [github front page](https://github.com/ofgulban/segmentator#installation--quick-start). This should install version 1.5.3 (and I think it does), but at commandline, during segmentator startup, it prints `Segmentator 1.5.2`.

This is probably because `version='1.5.2'` in `setup.py`. Making a pull request doesn't make sense, but in the next release the `version` flag should be incremented accordingly to avoid confusion.

**Comment by ofgulban** [comment]
Thanks, I have updated the version number in setup.py in devel branch. I will actually have a look at this draw order issue and release 1.5.4 afterwards.
