### ISSUE TITLE
coronal view

### ISSUE THREAD

**Issue by ingo-m** [ofgulban/segmentator#9]
Bug in segmentator-devel-marian:

When looping through the different volume views (axial, sagittal, coronal) with the "cycle view" button, the coronal view is not displayed (the previews view stays on the screen). When using the slider then, the coronal view is displayed.

Dataset:

/Uitwisseling/ParCon/20151130_02/20150930_02_T1.nii.gz

Error message (which appears after clicking the "cycle view" button, when the coronal view should appear):

> Exception in Tkinter callback
> Traceback (most recent call last):
>  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1535, in __call__
>    return self.func(*args)
>  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 416, in button_release_event
>    FigureCanvasBase.button_release_event(self, x, y, num, guiEvent=event)
>  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 1893, in button_release_event
>    self.callbacks.process(s, event)
>  File "/usr/lib/python2.7/dist-packages/matplotlib/cbook.py", line 540, in process
>    proxy(*args, **kwargs)
>  File "/usr/lib/python2.7/dist-packages/matplotlib/cbook.py", line 415, in __call__
>    return mtd(*args, **kwargs)
>  File "/usr/lib/python2.7/dist-packages/matplotlib/widgets.py", line 215, in _release
>    func(event)
>  File "./segmentator_main.py", line 203, in cycleView
>    slc.set_data(orig[:, :, drSectorObj.sector.sliceNr])
> IndexError: index 121 is out of bounds for axis 2 with size 88

**Comment by MSchnei** [comment]
This (probably) results from the fact that for the data that you were using there were only very few coronal slices. Problematically, the slice number was not updated flexibly as to always be in the middle of the slices after clicking the 'cycle view' button. When trying to access a high slice number (value for slice number is still high from sagittal or transverse view), this will yield too high of value for the few coronal slices.
The solution is to always set the value for slice number to half of the total number of slices, as was already done for the image browser update. This is now also implemented when  the 'cycle view' button was pressed. The issue should thus be resolved now.
